name: Test & Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        env:
          CI: true
        run: |
          npm ci

      - name: Run tests
        run: |
          npm test

  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: "18"


      - name: Install dependencies
        env:
          CI: true
        run: |
          npm ci

      - name: Build package
        run: npm run build

      - name: Authenticate for GitHub Packages
        env:
          TOKEN: ${{ secrets.PUBLISHING_TOKEN }}
          REGISTRY: 'https://npm.pkg.github.com'
        run: |
          npm config set @noodle-group:registry $REGISTRY
          npm config set //npm.pkg.github.com/:_authToken $TOKEN
          npm login --scope=@noodle-group --auth-type=legacy --registry=$NPM_REGISTRY

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISHING_TOKEN }}
