name: Run Tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        env:
          CI: true
        run: |
          npm ci

      - name: Run tests
        run: |
          npm test